### ISSUE TITLE
All tests fail with Jest 27

### ISSUE THREAD

**Issue by martinfrancois** [ricardo-ch/jest-fail-on-console#4]
After upgrading to Jest 27, every test fails with this error:
```
    Test did not tear down console.error mock properly.
        
        If you are trying to disable the "fail on console" mechanism, you should use beforeEach/afterEach
        instead of beforeAll/afterAll

          
      at flushUnexpectedConsoleCalls (node_modules/jest-fail-on-console/index.js:31:13)
      at Object.flushAllUnexpectedConsoleCalls (node_modules/jest-fail-on-console/index.js:77:7)
```
This didn't occur with Jest 26.

We are using a `testSetupAfterEnv.ts` file with the following content:
```
import failOnConsole from 'jest-fail-on-console';
failOnConsole();
```

And the following jest config:
```
  "jest": {
    "testEnvironment": "jsdom",
    "transform": {
      "^.+\\.(js|jsx|ts|tsx)$": "<rootDir>/node_modules/babel-jest"
    },
    "transformIgnorePatterns": [
      "/node_modules/",
      "^.+\\.module\\.(css|sass|scss)$"
    ],
    "moduleDirectories": [
      "node_modules",
      "src",
      "pages"
    ],
    "setupFilesAfterEnv": [
      "./src/testSetupAfterEnv.ts"
    ]
  },
```

**Comment by martinfrancois** [comment]
Upon closer investigation, I found the reason for the failing tests, see here: https://react-hooks-testing-library.com/installation#pure-imports
It mentions `console.error is patched to hide some React errors`, and in fact if I replace the following import:
```
import { renderHook } from '@testing-library/react-hooks/pure';
```
With this import:
```
import { renderHook } from '@testing-library/react-hooks';
```
I don't see the error anymore, but also the side effects performed by `@testing-library/react-hooks` are not executed.

Is there any way to make `jest-fail-on-console` restore the mock if it is patched as it is by `@testing-library/react-hooks`, to get rid of the error?

**Comment by ValentinH** [comment]
Thanks for sharing this solution. I actually faced the exact same issue a few weeks ago and solved it by using the `/pure` version. On my case, not having the side effect run was not an issue.

The problem is that `@testing-library/react-hooks` isn't using a Jest mock (they support other test runners) to patch the console so I don't know how to make an exception for it.

**Comment by pietmichal** [comment]
My temporary solution is to mock error implementation in `beforeEach` hook.

```javascript
beforeEach(() => {
  jest.spyOn(console, "error").mockImplementation();
});
```

**Comment by jgabriele** [comment]
My colleague @KevinHerklotz fixed it in a more robust way:

```typescript
setupFilesAfterEnv: [
    '@testing-library/react-hooks/disable-error-filtering.js',
    // other setup
]
```

More infos here: https://react-hooks-testing-library.com/reference/api#consoleerror

Could it be an option for you @martinfrancois?
